[package]
name = "Savior_Be"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7.5"
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.5.2", features = ["fs"] }
hyper = { version = "0.14.27", features=["full"]}
